package pojo;

// Generated 29-avr.-2014 11:57:26 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Adresse generated by hbm2java
 */
@Entity
@Table(name = "adresse", catalog = "argentinosll")
public class Adresse implements java.io.Serializable {

	private String nom;
	private Clubadverse clubadverse;
	private String lieux;

	public Adresse() {
	}

	public Adresse(Clubadverse clubadverse, String lieux) {
		this.clubadverse = clubadverse;
		this.lieux = lieux;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "clubadverse"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "Nom", unique = true, nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Clubadverse getClubadverse() {
		return this.clubadverse;
	}

	public void setClubadverse(Clubadverse clubadverse) {
		this.clubadverse = clubadverse;
	}

	@Column(name = "Lieux", nullable = false, length = 100)
	public String getLieux() {
		return this.lieux;
	}

	public void setLieux(String lieux) {
		this.lieux = lieux;
	}

}
