package pojo;

// Generated 29-avr.-2014 11:57:26 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Arbitre generated by hbm2java
 */
@Entity
@Table(name = "arbitre", catalog = "argentinosll")
public class Arbitre implements java.io.Serializable {

	private int numeroDeMatch;
	private Matchs matchs;
	private String nom;
	private String prenom;

	public Arbitre() {
	}

	public Arbitre(Matchs matchs, String nom, String prenom) {
		this.matchs = matchs;
		this.nom = nom;
		this.prenom = prenom;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "matchs"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "NumeroDeMatch", unique = true, nullable = false)
	public int getNumeroDeMatch() {
		return this.numeroDeMatch;
	}

	public void setNumeroDeMatch(int numeroDeMatch) {
		this.numeroDeMatch = numeroDeMatch;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Matchs getMatchs() {
		return this.matchs;
	}

	public void setMatchs(Matchs matchs) {
		this.matchs = matchs;
	}

	@Column(name = "Nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "Prenom", nullable = false, length = 50)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

}
