package pojo;
// Generated 29-avr.-2014 11:57:26 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Calendrier generated by hbm2java
 */
@Entity
@Table(name="calendrier"
    ,catalog="argentinosll"
)
public class Calendrier  implements java.io.Serializable {


     private int numeroDeMatch;
     private Matchs matchs;
     private Club club;
     private Date date;
     private String heure;
     private String serie;
     private String equipeAdverse;
     private String dom,ext;
     private Engendre engendre;

    public Calendrier() {
    }

	
    public Calendrier(Matchs matchs, Club club, Date date, String heure, String serie, String equipeAdverse, String dom, String ext) {
        this.matchs = matchs;
        this.club = club;
        this.date = date;
        this.heure = heure;
        this.serie = serie;
        this.equipeAdverse = equipeAdverse;
        this.dom = dom;
        this.ext = ext;
    }
    public Calendrier(Matchs matchs, Club club, Date date, String heure, String serie, String equipeAdverse, String dom, String ext, Engendre engendre) {
       this.matchs = matchs;
       this.club = club;
       this.date = date;
       this.heure = heure;
       this.serie = serie;
       this.equipeAdverse = equipeAdverse;
       this.dom = dom;
       this.ext = ext;
       this.engendre = engendre;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="matchs"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="NumeroDeMatch", unique=true, nullable=false)
    public int getNumeroDeMatch() {
        return this.numeroDeMatch;
    }
    
    public void setNumeroDeMatch(int numeroDeMatch) {
        this.numeroDeMatch = numeroDeMatch;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Matchs getMatchs() {
        return this.matchs;
    }
    
    public void setMatchs(Matchs matchs) {
        this.matchs = matchs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Matricule", nullable=false)
    public Club getClub() {
        return this.club;
    }
    
    public void setClub(Club club) {
        this.club = club;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="Heure", nullable=false, length=10)
    public String getHeure() {
        return this.heure;
    }
    
    public void setHeure(String heure) {
        this.heure = heure;
    }

    
    @Column(name="Serie", nullable=false, length=20)
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }

    
    @Column(name="EquipeAdverse", nullable=false, length=30)
    public String getEquipeAdverse() {
        return this.equipeAdverse;
    }
    
    public void setEquipeAdverse(String equipeAdverse) {
        this.equipeAdverse = equipeAdverse;
    }

    
    @Column(name="DOM/EXT", nullable=false)
    public String getDom() {
        return this.dom;
    }
    public String getExt() {
    	return this.ext;
    }
    
    public void setDom(String dom) {
        this.dom = dom;
    }
    public void setExt(String ext) {
        this.ext = ext;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="calendrier")
    public Engendre getEngendre() {
        return this.engendre;
    }
    
    public void setEngendre(Engendre engendre) {
        this.engendre = engendre;
    }




}


