package pojo;

// Generated 29-avr.-2014 11:57:26 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Club generated by hbm2java
 */
@Entity
@Table(name = "club", catalog = "argentinosll")
public class Club implements java.io.Serializable {

	private int matricule;
	private String nom;
	private String president;
	private String cq;
	private String adresse;
	private String EMail;
	private long telephone;
	private Set<Calendrier> calendriers = new HashSet<Calendrier>(0);
	private Set<Equipes> equipeses = new HashSet<Equipes>(0);

	public Club() {
	}

	public Club(int matricule, String nom, String president, String cq,
			String adresse, String EMail, long telephone) {
		this.matricule = matricule;
		this.nom = nom;
		this.president = president;
		this.cq = cq;
		this.adresse = adresse;
		this.EMail = EMail;
		this.telephone = telephone;
	}

	public Club(int matricule, String nom, String president, String cq,
			String adresse, String EMail, long telephone,
			Set<Calendrier> calendriers, Set<Equipes> equipeses) {
		this.matricule = matricule;
		this.nom = nom;
		this.president = president;
		this.cq = cq;
		this.adresse = adresse;
		this.EMail = EMail;
		this.telephone = telephone;
		this.calendriers = calendriers;
		this.equipeses = equipeses;
	}

	@Id
	@Column(name = "Matricule", unique = true, nullable = false)
	public int getMatricule() {
		return this.matricule;
	}

	public void setMatricule(int matricule) {
		this.matricule = matricule;
	}

	@Column(name = "Nom", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "President", nullable = false, length = 20)
	public String getPresident() {
		return this.president;
	}

	public void setPresident(String president) {
		this.president = president;
	}

	@Column(name = "CQ", nullable = false, length = 20)
	public String getCq() {
		return this.cq;
	}

	public void setCq(String cq) {
		this.cq = cq;
	}

	@Column(name = "Adresse", nullable = false, length = 100)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "E_mail", nullable = false, length = 50)
	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	@Column(name = "Telephone", nullable = false, precision = 15, scale = 0)
	public long getTelephone() {
		return this.telephone;
	}

	public void setTelephone(long telephone) {
		this.telephone = telephone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "club")
	public Set<Calendrier> getCalendriers() {
		return this.calendriers;
	}

	public void setCalendriers(Set<Calendrier> calendriers) {
		this.calendriers = calendriers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "club")
	public Set<Equipes> getEquipeses() {
		return this.equipeses;
	}

	public void setEquipeses(Set<Equipes> equipeses) {
		this.equipeses = equipeses;
	}

}
