package pojo;

// Generated 29-avr.-2014 11:57:26 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coupe generated by hbm2java
 */
@Entity
@Table(name = "coupe", catalog = "argentinosll")
public class Coupe implements java.io.Serializable {

	private char coupe;
	private String serie;
	private String equipeAdverse;
	private String niveau;
	private String score;
	private Set<Matchs> matchses = new HashSet<Matchs>(0);

	public Coupe() {
	}

	public Coupe(char coupe, String serie, String equipeAdverse, String niveau,
			String score) {
		this.coupe = coupe;
		this.serie = serie;
		this.equipeAdverse = equipeAdverse;
		this.niveau = niveau;
		this.score = score;
	}

	public Coupe(char coupe, String serie, String equipeAdverse, String niveau,
			String score, Set<Matchs> matchses) {
		this.coupe = coupe;
		this.serie = serie;
		this.equipeAdverse = equipeAdverse;
		this.niveau = niveau;
		this.score = score;
		this.matchses = matchses;
	}

	@Id
	@Column(name = "Coupe", unique = true, nullable = false, length = 1)
	public char getCoupe() {
		return this.coupe;
	}

	public void setCoupe(char coupe) {
		this.coupe = coupe;
	}

	@Column(name = "Serie", nullable = false, length = 20)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@Column(name = "EquipeAdverse", nullable = false, length = 30)
	public String getEquipeAdverse() {
		return this.equipeAdverse;
	}

	public void setEquipeAdverse(String equipeAdverse) {
		this.equipeAdverse = equipeAdverse;
	}

	@Column(name = "niveau", nullable = false, length = 5)
	public String getNiveau() {
		return this.niveau;
	}

	public void setNiveau(String niveau) {
		this.niveau = niveau;
	}

	@Column(name = "score", nullable = false, length = 4)
	public String getScore() {
		return this.score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coupe")
	public Set<Matchs> getMatchses() {
		return this.matchses;
	}

	public void setMatchses(Set<Matchs> matchses) {
		this.matchses = matchses;
	}

}
