package pojo;

// Generated 29-avr.-2014 11:57:26 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Delegue generated by hbm2java
 */
@Entity
@Table(name = "delegue", catalog = "argentinosll", uniqueConstraints = @UniqueConstraint(columnNames = "Telephone"))
public class Delegue implements java.io.Serializable {

	private int identifiant;
	private String telephone;
	private String nom;
	private String prenom;
	private String serie;
	private Set<Equipes> equipeses = new HashSet<Equipes>(0);

	public Delegue() {
	}

	public Delegue(int identifiant, String telephone, String nom,
			String prenom, String serie) {
		this.identifiant = identifiant;
		this.telephone = telephone;
		this.nom = nom;
		this.prenom = prenom;
		this.serie = serie;
	}

	public Delegue(int identifiant, String telephone, String nom,
			String prenom, String serie, Set<Equipes> equipeses) {
		this.identifiant = identifiant;
		this.telephone = telephone;
		this.nom = nom;
		this.prenom = prenom;
		this.serie = serie;
		this.equipeses = equipeses;
	}

	@Id
	@Column(name = "Identifiant", unique = true, nullable = false)
	public int getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(int identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "Telephone", unique = true, nullable = false, length = 25)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "Nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "Prenom", nullable = false, length = 50)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "Serie", nullable = false, length = 20)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "delegue")
	public Set<Equipes> getEquipeses() {
		return this.equipeses;
	}

	public void setEquipeses(Set<Equipes> equipeses) {
		this.equipeses = equipeses;
	}

}
