package pojo;

// Generated 29-avr.-2014 11:57:26 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Equipes generated by hbm2java
 */
@Entity
@Table(name = "equipes", catalog = "argentinosll", uniqueConstraints = @UniqueConstraint(columnNames = "Identifiant"))
public class Equipes implements java.io.Serializable {

	private String serie;
	private Delegue delegue;
	private Club club;
	private String coach;
	private int anneeCategorie;
	private Set<Matchs> matchses = new HashSet<Matchs>(0);
	private Set<EquipesJoueurs> equipesJoueurses = new HashSet<EquipesJoueurs>(
			0);

	public Equipes() {
	}

	public Equipes(String serie, Delegue delegue, Club club, String coach,
			int anneeCategorie) {
		this.serie = serie;
		this.delegue = delegue;
		this.club = club;
		this.coach = coach;
		this.anneeCategorie = anneeCategorie;
	}

	public Equipes(String serie, Delegue delegue, Club club, String coach,
			int anneeCategorie, Set<Matchs> matchses,
			Set<EquipesJoueurs> equipesJoueurses) {
		this.serie = serie;
		this.delegue = delegue;
		this.club = club;
		this.coach = coach;
		this.anneeCategorie = anneeCategorie;
		this.matchses = matchses;
		this.equipesJoueurses = equipesJoueurses;
	}

	@Id
	@Column(name = "Serie", unique = true, nullable = false, length = 50)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Identifiant", unique = true, nullable = false)
	public Delegue getDelegue() {
		return this.delegue;
	}

	public void setDelegue(Delegue delegue) {
		this.delegue = delegue;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Matricule", nullable = false)
	public Club getClub() {
		return this.club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	@Column(name = "Coach", nullable = false, length = 50)
	public String getCoach() {
		return this.coach;
	}

	public void setCoach(String coach) {
		this.coach = coach;
	}

	@Column(name = "AnneeCategorie", nullable = false)
	public int getAnneeCategorie() {
		return this.anneeCategorie;
	}

	public void setAnneeCategorie(int anneeCategorie) {
		this.anneeCategorie = anneeCategorie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipes")
	public Set<Matchs> getMatchses() {
		return this.matchses;
	}

	public void setMatchses(Set<Matchs> matchses) {
		this.matchses = matchses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipes")
	public Set<EquipesJoueurs> getEquipesJoueurses() {
		return this.equipesJoueurses;
	}

	public void setEquipesJoueurses(Set<EquipesJoueurs> equipesJoueurses) {
		this.equipesJoueurses = equipesJoueurses;
	}

}
