package pojo;

// Generated 29-avr.-2014 11:57:26 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * EquipesJoueurs generated by hbm2java
 */
@Entity
@Table(name = "equipes_joueurs", catalog = "argentinosll")
public class EquipesJoueurs implements java.io.Serializable {

	private int numeroDaffiliation;
	private Equipes equipes;
	private Joueurs joueurs;
	private String nom;
	private String prenom;
	private String anneeCategorie;

	public EquipesJoueurs() {
	}

	public EquipesJoueurs(Equipes equipes, Joueurs joueurs, String nom,
			String prenom, String anneeCategorie) {
		this.equipes = equipes;
		this.joueurs = joueurs;
		this.nom = nom;
		this.prenom = prenom;
		this.anneeCategorie = anneeCategorie;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "joueurs"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "NumeroDAffiliation", unique = true, nullable = false)
	public int getNumeroDaffiliation() {
		return this.numeroDaffiliation;
	}

	public void setNumeroDaffiliation(int numeroDaffiliation) {
		this.numeroDaffiliation = numeroDaffiliation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Serie", nullable = false)
	public Equipes getEquipes() {
		return this.equipes;
	}

	public void setEquipes(Equipes equipes) {
		this.equipes = equipes;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Joueurs getJoueurs() {
		return this.joueurs;
	}

	public void setJoueurs(Joueurs joueurs) {
		this.joueurs = joueurs;
	}

	@Column(name = "Nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "Prenom", nullable = false, length = 50)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "AnneeCategorie", nullable = false, length = 4)
	public String getAnneeCategorie() {
		return this.anneeCategorie;
	}

	public void setAnneeCategorie(String anneeCategorie) {
		this.anneeCategorie = anneeCategorie;
	}

}
