package pojo;

// Generated 29-avr.-2014 11:57:26 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Suspensions generated by hbm2java
 */
@Entity
@Table(name = "suspensions", catalog = "argentinosll")
public class Suspensions implements java.io.Serializable {

	private int numeroDaffiliation;
	private Joueurs joueurs;
	private String nom;
	private String prenom;
	private String motif;
	private Date duree;

	public Suspensions() {
	}

	public Suspensions(Joueurs joueurs, String nom, String prenom,
			String motif, Date duree) {
		this.joueurs = joueurs;
		this.nom = nom;
		this.prenom = prenom;
		this.motif = motif;
		this.duree = duree;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "joueurs"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "NumeroDAffiliation", unique = true, nullable = false)
	public int getNumeroDaffiliation() {
		return this.numeroDaffiliation;
	}

	public void setNumeroDaffiliation(int numeroDaffiliation) {
		this.numeroDaffiliation = numeroDaffiliation;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Joueurs getJoueurs() {
		return this.joueurs;
	}

	public void setJoueurs(Joueurs joueurs) {
		this.joueurs = joueurs;
	}

	@Column(name = "Nom", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "Prenom", nullable = false, length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "Motif", nullable = false, length = 100)
	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Duree", nullable = false, length = 10)
	public Date getDuree() {
		return this.duree;
	}

	public void setDuree(Date duree) {
		this.duree = duree;
	}

}
